name: Build React App on PR or Merge

on:
  push:
    branches:
      - main    # triggers after PR is merged into main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]  # runs on PR events

jobs:
  build:
    runs-on: self-hosted   # or 'ubuntu-latest' if you want GitHub-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build
