name: Build & Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Debug repository structure
      - name: Debug Repository
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Node version: $(node -v)"
          echo "npm version: $(npm -v)"

      # Step 3: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: |
          npm ci
          echo "Installed dependencies:"
          ls -la node_modules

      # Step 5: Build React App with Parcel
      - name: Build React App
        run: |
          echo "Starting Parcel build..."
          set -o pipefail
          npm run build 2>&1 | tee build.log

      # Step 6: List directory after build
      - name: List Directory After Build
        run: |
          echo "Current directory after build: $(pwd)"
          ls -la

      # Step 7: Verify dist folder
      - name: Verify dist Folder
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist folder not found!"
            cat build.log || true
            exit 1
          fi
          ls -la dist

      # Step 8: Deploy Build
      - name: Deploy Build
        run: |
          mkdir -p /home/aakash/react-app
          rm -rf /home/aakash/react-app/* || true
          cp -r dist/* /home/aakash/react-app/

      # Step 9: Restart Serve with PM2
      - name: Restart Serve with PM2
        run: |
          npm install -g serve pm2
          pm2 delete react-app || true
          pm2 start "serve -s /home/aakash/react-app -l 3000" --name react-app
          pm2 save
